spring:
  datasource:
    url: jdbc:mysql://localhost:3306/festival_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root # 실제 MySQL 사용자명으로 변경
    password: 1234 # 실제 MySQL 비밀번호로 변경
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create-drop, create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # Gmail SMTP 설정 추가
  mail:
    host: smtp.gmail.com
    port: 587
    username: rlaxodus2331@gmail.com
    password: bqcf ijnm mzqx skez
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
    test-connection: false

  # 비동기 처리 설정
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: email-

server:
  port: 8081

# JWT 설정
app:
  jwtSecret: 46930c6e2098076c2ffdc8f1de5d7095debe589eea5b0f43819599a3749d88e26fff284659a26f4baecffc1e7ba574d24d4da5164bf2cf21670ce983d58eb91c
  jwtExpirationInMs: 604800000 # 7일
  name: Festival App # 이메일에서 사용할 앱 이름

logging:
  level:
    com.korea.festival: DEBUG
    org.springframework.security: DEBUG
    # 이메일 관련 로그 추가
    com.korea.festival.service.EmailService: DEBUG
    org.springframework.mail: INFO
    org.springframework.mail.javamail: DEBUG

kakao:
  client-id: 053daa073678f270e103f9f9add52992
  client-secret: MNDZVunCq1OO9mirfTYEM1S8YixLbZrT

# 이메일 설정 (선택사항 - 추가 커스터마이징)
email:
  # 발신자 정보
  from:
    name: Festival App
    address: xodus2331@naver.com
  
  # 템플릿 설정
  templates:
    temp-password:
      subject: "[Festival App] 임시 비밀번호 발송"
    welcome:
      subject: "[Festival App] 회원가입을 환영합니다!"
  
  # 재시도 설정
  retry:
    max-attempts: 3
    delay: 1000